menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- recent_posts
- recent_comment
- tagcloud 

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false

fancybox: true

google_analytics: UA-41590217-1
rss: /atom.xml

