menu:
  关于: /about
  阅读: /reading
  电影: /film  
  归档: /archives

widgets:  

excerpt_link: More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false

fancybox: true

google_analytics: 
rss:

favicon: /source/favicon.ico
