menu: 
  - title: 关于
    url: about
    #intro: "关于懒人"
    icon: "icon-user"
  - title: 归档
    url: archives
    #intro: "全部归档"
    icon: "icon-key"
  - title: 阅读
    url: reading
    #intro: "阅读"
    icon: "icon-book"
  - title: 电影
    url: film
    #intro: "电影"
    icon: "icon-film"

widgets:
- about_me
- recent_posts
- category
- tagcloud
- link

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false

fancybox: true

google_analytics: 
rss:

favicon: favicon.ico

about_me:
  img: about_me.jpg
  texts:
  - <a href="/about" target="_BLANK">WangChen(Liz)</a>
  - 位置：北京 天津 青岛
  - 角色：伪搬砖 前PM
  - 技能：暂无
 # - <img src="/uploads/email.gif">

duoshuo: iwangchen
share: true
baidu_tongji: true

links:
  - title: Homepage
    url: http://iwangchen.com
    icon: "icon-flag"
  - title: "Github"
    url: https://www.github.com/lizzzz
    icon: "icon-github-alt"
