menu: 
  - title: 首页
    url: 
    #intro: "首页"
    icon: "fa fa-flash on fa-fw"
  - title: 关于
    url: about
    #intro: "关于"
    icon: "fa fa-meh-o fa-fw"
  - title: 归档
    url: archives
    #intro: "归档"
    icon: "fa fa-clone fa-fw"
  - title: 阅读
    url: reading
    #intro: "阅读"
    icon: "fa fa-venus-mars fa-fw"
  - title: 电影
    url: film
    #intro: "电影"
    icon: "fa fa-tv fa-fw"

widgets:
- about_me
- recent_posts
- category
- tagcloud
- link

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 9

addthis:
  enable: false

fancybox: true

google_analytics: 
rss:

favicon: img/iwangchen.ico

about_me:
  img: about_me.jpg
  texts:
  - <a href="/about" target="_BLANK">Wang Chen (Liz)</a>
  - 位置：北京 天津 青岛
  - 角色：金融搬砖工
  - 描述：一枚傲娇的懒大王
  github: img/icons/github_icon.png
  weibo: img/icons/weibo_icon.png
  douban: img/icons/douban_icon.png
  zhihu: img/icons/zhihu_icon.png
  linkedin: img/icons/linkedin_icon.png
  qq: img/icons/qq_icon.png

duoshuo: iwangchen
share: true
baidu_tongji: true

links:
  - title: 羊毛党俱乐部 | 一起薅羊毛吧
    url: http://ymd.club
    #icon: "icon-gift"
  - title: Github
    url: https://www.github.com/lizzzz
    #icon: "icon-github-alt"
  - title: Homepage
    url: http://iwangchen.com
    #icon: "icon-flag"