menu: 
  - title: 关于
    url: about
    #intro: "关于懒人"
    icon: "icon-user"
  - title: 归档
    url: archives
    #intro: "全部归档"
    icon: "icon-key"
  - title: 阅读
    url: reading
    #intro: "阅读"
    icon: "icon-book"
  - title: 电影
    url: film
    #intro: "电影"
    icon: "icon-film"

widgets:
- about_me

excerpt_link: More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false

fancybox: true

google_analytics: 
rss:

favicon: favicon.ico

about_me:
  img: about_me.jpg
  texts:
  - <hr>
  - <a href="/about" target="_BLANK">懒人(Liz)</a>
  - 这个家伙很懒，没有签名档。
  - <br>
 # - <img src="/uploads/email.gif">
